### ISSUE TITLE
Differences between versions?

### ISSUE THREAD

**Issue by adrientetar** [servo/pathfinder#107]
Context: I'm looking to implement pathfinder in C to evaluate text rendering algorithms.

@pcwalton Can you describe the differences between Pathfinder 1, 2 and 3? It seems Pathfinder 3 does more/most of the work on the CPU compared to the original version. Why the change?

**Comment by LifeIsStrange** [comment]
If data upload latency to the gpu was the bottleneck, why not choose SIMD x86 instructions which allow great parallelism without the latency.
https://en.m.wikipedia.org/wiki/SIMD

**Comment by pcwalton** [comment]
@adrientetar  This will be explained in an upcoming blog post. Briefly, though: For text rendering, PF3 and PF2 are almost the same except that PF3 does the curve-to-line approximation on CPU instead of GPU, and PF3 has a tiling step on CPU to reduce the asymptotic complexity for large glyphs. I moved the curve-to-line approximation from GPU to CPU because (a) it's higher-quality (no longer sensitive to choice of axis); (b) more work-efficient to do it that way; (c) I already had to approximate cubics with quadratics on CPU, so CFF outlines had a CPU step already; (d) tiling is much easier when you don't have to solve curve equations. For SVG, I felt PF2's tessellating renderer to be a dead end, because (a) generating the bounding geometry necessary to render antialiased curves was difficult and resulted in tons of microtriangles; (b) dealing with self-intersecting paths properly was too fragile. PF3 has a unified renderer for both text and SVG, and the tiling provides a natural way to achieve occlusion culling.

I could move more of this to the GPU over time, taking advantage of new GPU features such as compute shaders where they're available to do the tiling, sort of like Skia Compute does (though I think PF3's tiling algorithm is significantly more efficient than that of Skia Compute). But right now, I can pipeline effectively between CPU and GPU, running CPU and GPU *at the same time*, so it's fairly low-priority. If you're going to benchmark, please keep the pipelining in mind. For example, if you're bulk rendering many glyphs, PF3 works best if you divide up the glyphs into batches and render batch 1 on GPU while you're preparing batch 2 on CPU, etc.

@LifeIsStrange PF3 already uses SIMD and multicore extensively.

**Comment by pcwalton** [comment]
By the way, I wouldn't say Pathfinder 3 does most of the work on CPU. It simply uses the CPU for what it's good at and uses the GPU for what it's good at. I try to keep the workloads balanced at roughly 50/50 on most hardware in order to make best use as much of the silicon as possible. (Remember that the two phases can be pipelined.)

**Comment by pcwalton** [comment]
See #119 for ideas on moving more of PF3 to the GPU.

**Comment by adrientetar** [comment]
@pcwalton Thanks, also what's the difference between PF1 and 2? : )

**Comment by pcwalton** [comment]
Pathfinder 1 did summed area calculation like `font-rs` does in compute shader. Pathfinder 2 was a hybrid approach that used tessellation for SVG and essentially used Pathfinder 3's approach, minus the tiling, for fonts. Pathfinder 3 removes the tessellation and adds tiling for a single unified algorithm.

**Comment by pcwalton** [comment]
This should be answered now. Closing.

**Comment by pcwalton** [comment]
I should mention that https://nical.github.io/posts/a-look-at-pathfinder.html is a good overview of Pathfinder 3's approach.
