### ISSUE TITLE
Consider using F64x2 instead of F32x4 for 2D vectors

### ISSUE THREAD

**Issue by pcwalton** [servo/pathfinder#207]
Two of the SIMD lanes go unused. According to Agner's tables, F64x2 is just as fast as F32x4 for most operations on Skylake, so we might as well get the extra precision instead of wasting the space. This might improve clipping a bit.

**Comment by pcwalton** [comment]
On AArch64 we should probably continue to use 32-bit, though, because that reduces register pressure.

**Comment by pcwalton** [comment]
Conditionally using 64-bit turns out to be a bad idea. I have a WIP branch that uses two 32-bit values to save memory, which is much better and works great on x86.

**Comment by s3bk** [comment]
For reference: [ReX](https://github.com/retex/ReX) uses 24.8 fixed point for coordinates, mostly because that is what TrueType uses and we wanted the most performance on systems without floating point instructions. Converting that to f32 would loose a few bits. On a 1m scale f32 has an error of about 60µm. I don't think f64 is necessary, but it would be a neat extra.

**Comment by pcwalton** [comment]
Fixed in https://github.com/servo/pathfinder/commit/b886c157c18b52881013ac029642450cc07e9bb9.
