### ISSUE TITLE
Clipping and FillRule appear to be broken.

### ISSUE THREAD

**Issue by s3bk** [servo/pathfinder#269]
When clipping against the upper edge, this happens: 
<img width="85" alt="grafik" src="https://user-images.githubusercontent.com/48330868/75090492-7e321480-5574-11ea-9455-73874df3ae79.png">

Unclipped it renders properly:
<img width="85" alt="grafik" src="https://user-images.githubusercontent.com/48330868/75090495-88541300-5574-11ea-8e02-be2b76254351.png">

It only appears to affect paths with holes in them. `FillRule::Winding` is used.

**Comment by Frizi** [comment]
I've had similar issue using your font library. It seems like the clipping is behaving weirdly if you are using non-closed contours to perform fills. The clipping logic is not performing a clip after the implied last edge if the conotur is not declared to be closed. In this case, that edge happens to be on the left of "D" letter. As the topmost segment is clipped out completely, the new implied edge is between new first and last vertices, cutting through the whole letter.

As fonts require that all contours are closed, the fix for me was to call `contour.close()` on every contour from the glyph path.

**Comment by s3bk** [comment]
Why did I not see your reply earlier… 
@Frizi I indeed call `contour.close()` on every contour:
https://github.com/pdf-rs/font/blob/85353fe5921179eb17c8740e7f11ded8498fdd5d/src/truetype.rs#L363

**Comment by s3bk** [comment]
Sooooo after lots of investigations:
```svg
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 640 480">
<path transform="scale(50) translate(0,-3)" d="
m 2,8
h 2.481781
c   1.8912573,0
    2.3780413,-1.77156
    2.3780413,-3.00048
c   0,-1.08529
    -0.399004,-2.7291599
    -2.3301643,-2.7291599
h -2.529658

z

M 3,3
h 1.14912
c   0.510719,0
    1.3167,0.13566
    1.3167,1.8274199
c   0,0.94164
    -0.327184,1.92318 
    -1.300739,1.92318
h -1.165081
z
"
style="fill:#000000;fill-rule:nonzero" />
</svg>
```

The `z` in the middle makes pathfinder clip the path correct. I don't think it should be required. Inkscape and firefox are just fine without it.
